const CONNECT_WALLET = 'CONNECT_WALLET';
const DISCONNECT_WALLET = 'DISCONNECT_WALLET';
const GET_BALANCES = 'GET_BALANCES';
const LOADING = 'LOADING';
const ERROR = 'ERROR';

export { CONNECT_WALLET, DISCONNECT_WALLET, GET_BALANCES, LOADING, ERROR };
